Fix: GitHub workflows broken due to outdated versions / OS (#255)
# Summary <!-- Required -->

Updates the versions used for various actions to address:

> Error: This request has been automatically failed because it uses a
deprecated version of `actions/cache:
937d24475381cd9c75ae6db12cb4e79714b926ed`. Please update your workflow
to use v3/v4 of actions/cache to avoid interruptions. Learn more:
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

Also removes deprecated usage of ubuntu-20.04 -- see
https://github.com/actions/runner-images/issues/11101

Also updates the phpstan config to address an unrelated failure. See
https://github.com/10up/wp_mock/pull/255/files#r1983301587

## Details <!-- Optional -->

<!-- Please include a detailed explanation of the changes and/or the
reasoning behind them. -->

## Contributor checklist <!-- Required -->

<!--- Go over all the following points, and put an `x` in all the boxes
that apply. -->
<!--- If you are unsure about any of these, please ask for
clarification. We are here to help! -->

- [ ] I agree to follow this project's [**Code of
Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly 
- [ ] I have added tests to cover changes introduced by this pull
request
- [ ] All new and existing tests pass

## Testing <!-- Required -->

- [ ] Code review
- [ ] Checks pass / GH actions run successfully

### Reviewer checklist <!-- Required -->

<!-- The following checklist is for the reviewer: add any steps that may
be relevant while reviewing this pull request -->

- [ ] Code changes review
- [ ] Documentation changes review
- [ ] Unit tests pass
- [ ] Static analysis passes